//! Ferricula identity discovery — Docker-labelled identity containers (Steve
//! and friends) become MCP servers for every agent n8 launches.
//!
//! A Ferricula v2 identity is one server process in one container. Instead of
//! asking the user to hand-register each one, the launcher asks Docker: every
//! container carrying the `ferricula.identity` label is an identity. For each
//! running one n8 registers an MCP server for the launch, one of two ways:
//!
//! - **http** — the container serves Streamable-HTTP MCP itself (`POST /mcp`).
//!   n8 drops a server TOML into the user MCP dir the container already reads
//!   (`<data_home>/.nemesis8/mcp`, see [`crate::mcp_registry::host_user_mcp_dir`]).
//! - **bridge** — the identity ships a stdio bridge script (label
//!   `ferricula.bridge`, a Python file speaking MCP over stdio and REST to the
//!   identity). n8 copies it into the user tool dir (`<data_home>/mcp`, the
//!   same place `n8 mcp add` puts a `.py` tool) as `ferricula-<name>.py` with
//!   a small header that points it at the identity through
//!   `host.docker.internal` and at a token file n8 writes from the keychain.
//!
//! The bridge is used when the container's `/mcp` answers 404 (an older image)
//! and a bridge is labelled; otherwise http. Either way the server name goes on
//! `mcp_tools` for the launch and the token env on `env_imports`, so the bearer
//! is forwarded from the keychain like any imported secret. No image rebuild.
//!
//! Label contract (set on the identity's container, e.g. in its compose file):
//!
//! | label | meaning | default |
//! |---|---|---|
//! | `ferricula.identity` | the identity's short name; becomes the MCP server name | required |
//! | `ferricula.mcp_port` | HOST port the identity is published on | first published port |
//! | `ferricula.mcp_path` | path of the Streamable-HTTP MCP endpoint | `/mcp` |
//! | `ferricula.bridge` | stdio bridge script; a relative path is under the compose project dir | none |
//! | `ferricula.token_env` | env var holding the bearer token (forwarded from the keychain) | `FERRICULA_OPERATOR_TOKEN` |
//! | `ferricula.health_path` | unauthenticated route reporting `agent_id` and `mode` | `/health` |
//!
//! Opt out with `[integrations] ferricula_discovery = false`.

use serde::Serialize;
use std::collections::BTreeMap;
use std::path::{Path, PathBuf};

pub const LABEL_IDENTITY: &str = "ferricula.identity";
pub const LABEL_PORT: &str = "ferricula.mcp_port";
pub const LABEL_PATH: &str = "ferricula.mcp_path";
pub const LABEL_BRIDGE: &str = "ferricula.bridge";
pub const LABEL_TOKEN_ENV: &str = "ferricula.token_env";
pub const LABEL_HEALTH: &str = "ferricula.health_path";
const LABEL_COMPOSE_DIR: &str = "com.docker.compose.project.working_dir";
pub const DEFAULT_TOKEN_ENV: &str = "FERRICULA_OPERATOR_TOKEN";
/// First line of every file this module writes, so stale ones can be removed
/// without touching a user's hand-written files.
pub const GENERATED_MARK: &str = "# generated by n8 ferricula discovery — do not edit, it is rewritten at launch";
/// Where a bridge finds the identity's local inference service, as a container sees it.
const OLLAMA_CONTAINER_URL: &str = "http://host.docker.internal:11434";
/// Container HOME; `data_home` on the host maps here.
const CONTAINER_HOME: &str = "/opt/nemesis8";

/// How an identity is reached by the agent.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize)]
#[serde(rename_all = "lowercase")]
pub enum Transport {
    /// Streamable-HTTP MCP served by the container.
    Http,
    /// The identity's stdio bridge script, run by the container's Python.
    Bridge,
}

/// One discovered identity container.
#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
pub struct Identity {
    /// The `ferricula.identity` label, verbatim.
    pub name: String,
    /// Container name without the leading slash.
    pub container: String,
    /// Docker state: `running`, `exited`, …
    pub state: String,
    /// Host port the identity is published on.
    pub host_port: u16,
    pub mcp_path: String,
    /// Host path of the stdio bridge script, when labelled.
    pub bridge: Option<PathBuf>,
    pub token_env: String,
    pub health_path: String,
    /// From `GET /health`, when the probe succeeded.
    pub agent_id: Option<String>,
    /// From `GET /health`: `paused`, `active`, …
    pub mode: Option<String>,
    /// HTTP status of an unauthenticated `POST /mcp`, when probed. 404 means
    /// the running image has no MCP route.
    pub mcp_status: Option<u16>,
}

impl Identity {
    /// The MCP server name written into agent configs: lowercase, `[a-z0-9_-]`.
    pub fn server_name(&self) -> String {
        sanitize_name(&self.name)
    }

    /// The identity's base URL as a container sees it.
    pub fn container_base_url(&self) -> String {
        format!("http://host.docker.internal:{}", self.host_port)
    }

    /// The MCP endpoint as a container sees it.
    pub fn container_url(&self) -> String {
        format!("{}{}", self.container_base_url(), self.mcp_path)
    }

    /// The MCP endpoint as the host sees it.
    pub fn host_url(&self) -> String {
        format!("http://127.0.0.1:{}{}", self.host_port, self.mcp_path)
    }

    pub fn is_running(&self) -> bool {
        self.state == "running"
    }

    /// Bridge when the container has no MCP route (or was not probed) and a
    /// bridge script exists; otherwise http.
    pub fn transport(&self) -> Transport {
        let route_missing = matches!(self.mcp_status, None | Some(404));
        match &self.bridge {
            Some(p) if route_missing && p.is_file() => Transport::Bridge,
            _ => Transport::Http,
        }
    }

    /// The `mcp_tools` entry that enables this identity for a launch.
    pub fn tool_entry(&self) -> String {
        match self.transport() {
            Transport::Http => self.server_name(),
            Transport::Bridge => self.bridge_file_name(),
        }
    }

    /// File name of the generated http server TOML.
    pub fn toml_file_name(&self) -> String {
        format!("ferricula-{}.toml", self.server_name())
    }

    /// File name of the generated bridge wrapper.
    pub fn bridge_file_name(&self) -> String {
        format!("ferricula-{}.py", self.server_name())
    }

    /// Token file name under `<home>/.n8/ferricula/`.
    pub fn token_file_name(&self) -> String {
        format!("{}.token", self.server_name())
    }

    /// The `mcp-servers/*.toml`-shaped definition for the http transport.
    pub fn toml(&self) -> String {
        format!(
            "{GENERATED_MARK}\n# container {} · {}\n[server]\nname = \"{}\"\naliases = [\"ferricula-{}\"]\nurl = \"{}\"\ntransport = \"http\"\nbearer_token_env = \"{}\"\nenabled_by_default = true\n",
            self.container,
            self.agent_id.as_deref().unwrap_or("agent id unknown"),
            self.server_name(),
            self.server_name(),
            self.container_url(),
            self.token_env,
        )
    }

    /// The bridge script with n8's header: the identity's base URL and the
    /// inference URL as a container sees them, and the token file n8 wrote.
    /// `setdefault`, so a value already in the environment wins. The header
    /// goes after a shebang and after any `from __future__` lines, which
    /// Python requires first.
    pub fn bridge_wrapper(&self, source: &str) -> String {
        let header = format!(
            "{GENERATED_MARK}\n# identity {} · container {} · bridge {}\nimport os as _n8_os\n_n8_os.environ.setdefault(\"FERRICULA_BASE_URL\", \"{}\")\n_n8_os.environ.setdefault(\"OLLAMA_BASE_URL\", \"{OLLAMA_CONTAINER_URL}\")\n_n8_os.environ.setdefault(\"{}_FILE\", \"{}\")\n",
            self.name,
            self.container,
            self.bridge.as_deref().map(|p| p.display().to_string()).unwrap_or_default(),
            self.container_base_url(),
            self.token_env,
            format!("{CONTAINER_HOME}/.n8/ferricula/{}", self.token_file_name()),
        );
        let lines: Vec<&str> = source.lines().collect();
        // Insert after the last line the header may not precede.
        let mut at = 0;
        if lines.first().is_some_and(|l| l.starts_with("#!")) {
            at = 1;
        }
        if let Some(i) = lines.iter().rposition(|l| l.trim_start().starts_with("from __future__")) {
            at = at.max(i + 1);
        }
        let mut out = String::new();
        for l in &lines[..at] {
            out.push_str(l);
            out.push('\n');
        }
        out.push_str(&header);
        for l in &lines[at..] {
            out.push_str(l);
            out.push('\n');
        }
        out
    }
}

fn sanitize_name(raw: &str) -> String {
    let s: String = raw
        .to_lowercase()
        .chars()
        .map(|c| if c.is_ascii_alphanumeric() || c == '_' || c == '-' { c } else { '-' })
        .collect();
    s.trim_matches('-').to_string()
}

/// Is discovery on for this config? Default yes; `ferricula_discovery = false` turns it off.
pub fn enabled(config: &crate::config::Config) -> bool {
    config.integrations.ferricula_discovery.unwrap_or(true)
}

/// Parse `docker inspect` output in the format this module asks for, one
/// container per line: `<name>\t<state>\t<labels json>\t<ports json>`.
/// Lines without the identity label (or unparsable) are skipped.
pub fn parse_inspect_lines(text: &str) -> Vec<Identity> {
    let mut out = Vec::new();
    for line in text.lines() {
        let mut parts = line.splitn(4, '\t');
        let (Some(name), Some(state), Some(labels_json), Some(ports_json)) =
            (parts.next(), parts.next(), parts.next(), parts.next())
        else {
            continue;
        };
        let labels: BTreeMap<String, String> = serde_json::from_str(labels_json).unwrap_or_default();
        let Some(identity) = labels.get(LABEL_IDENTITY).map(|s| s.trim()).filter(|s| !s.is_empty()) else {
            continue;
        };
        let ports: serde_json::Value = serde_json::from_str(ports_json).unwrap_or(serde_json::Value::Null);
        let labelled_port = labels.get(LABEL_PORT).and_then(|p| p.trim().parse::<u16>().ok());
        let Some(host_port) = labelled_port.or_else(|| first_published_port(&ports)) else {
            continue;
        };
        let bridge = labels
            .get(LABEL_BRIDGE)
            .map(|p| p.trim())
            .filter(|p| !p.is_empty())
            .map(|p| {
                let path = PathBuf::from(p);
                if path.is_absolute() {
                    path
                } else {
                    match labels.get(LABEL_COMPOSE_DIR) {
                        Some(dir) => PathBuf::from(dir).join(path),
                        None => path,
                    }
                }
            });
        out.push(Identity {
            name: identity.to_string(),
            container: name.trim_start_matches('/').to_string(),
            state: state.trim().to_string(),
            host_port,
            mcp_path: labels
                .get(LABEL_PATH)
                .map(|p| p.trim().to_string())
                .filter(|p| p.starts_with('/'))
                .unwrap_or_else(|| "/mcp".to_string()),
            bridge,
            token_env: labels
                .get(LABEL_TOKEN_ENV)
                .map(|p| p.trim().to_string())
                .filter(|p| !p.is_empty())
                .unwrap_or_else(|| DEFAULT_TOKEN_ENV.to_string()),
            health_path: labels
                .get(LABEL_HEALTH)
                .map(|p| p.trim().to_string())
                .filter(|p| p.starts_with('/'))
                .unwrap_or_else(|| "/health".to_string()),
            agent_id: None,
            mode: None,
            mcp_status: None,
        });
    }
    out
}

/// The lowest host port in a `NetworkSettings.Ports` map
/// (`{"8875/tcp":[{"HostIp":"127.0.0.1","HostPort":"18875"}]}`).
fn first_published_port(ports: &serde_json::Value) -> Option<u16> {
    let map = ports.as_object()?;
    map.values()
        .filter_map(|v| v.as_array())
        .flatten()
        .filter_map(|b| b.get("HostPort").and_then(|p| p.as_str()).and_then(|p| p.parse::<u16>().ok()))
        .min()
}

/// Ask Docker for every container carrying the identity label. Empty when
/// Docker is unavailable or nothing is labelled.
pub fn discover(runtime: &str) -> Vec<Identity> {
    let ids = match std::process::Command::new(runtime)
        .args(["ps", "-a", "--filter", &format!("label={LABEL_IDENTITY}"), "-q"])
        .output()
    {
        Ok(o) if o.status.success() => String::from_utf8_lossy(&o.stdout)
            .lines()
            .map(|l| l.trim().to_string())
            .filter(|l| !l.is_empty())
            .collect::<Vec<_>>(),
        _ => return Vec::new(),
    };
    if ids.is_empty() {
        return Vec::new();
    }
    let mut cmd = std::process::Command::new(runtime);
    cmd.args([
        "inspect",
        "--format",
        "{{.Name}}\t{{.State.Status}}\t{{json .Config.Labels}}\t{{json .NetworkSettings.Ports}}",
    ]);
    cmd.args(&ids);
    match cmd.output() {
        Ok(o) if o.status.success() => parse_inspect_lines(&String::from_utf8_lossy(&o.stdout)),
        _ => Vec::new(),
    }
}

/// Fill `agent_id` / `mode` from the health route and `mcp_status` from an
/// unauthenticated `POST` to the MCP path (host side, 400 ms each). A failed
/// probe leaves the field `None`; the identity is still registered — the
/// agent's MCP client reports the real error at call time.
pub fn probe(id: &mut Identity) {
    let hostport = format!("127.0.0.1:{}", id.host_port);
    if let Some((_, body)) = http_request("GET", &hostport, &id.health_path, 400) {
        if let Ok(v) = serde_json::from_str::<serde_json::Value>(&body) {
            id.agent_id = v.get("agent_id").and_then(|s| s.as_str()).map(str::to_string);
            id.mode = v.get("mode").and_then(|s| s.as_str()).map(str::to_string);
        }
    }
    id.mcp_status = http_request("POST", &hostport, &id.mcp_path, 400).map(|(status, _)| status);
}

/// Minimal one-shot request; returns the status and the body's JSON object
/// text (or an empty string when there is none).
fn http_request(method: &str, hostport: &str, path: &str, timeout_ms: u64) -> Option<(u16, String)> {
    use std::io::{Read, Write};
    let addr: std::net::SocketAddr = hostport.parse().ok()?;
    let timeout = std::time::Duration::from_millis(timeout_ms);
    let mut stream = std::net::TcpStream::connect_timeout(&addr, timeout).ok()?;
    stream.set_read_timeout(Some(timeout)).ok()?;
    stream.set_write_timeout(Some(timeout)).ok()?;
    let body = if method == "POST" { "{}" } else { "" };
    let req = format!(
        "{method} {path} HTTP/1.1\r\nHost: {hostport}\r\nAccept: application/json\r\nContent-Type: application/json\r\nContent-Length: {}\r\nConnection: close\r\n\r\n{body}",
        body.len()
    );
    stream.write_all(req.as_bytes()).ok()?;
    let mut raw = Vec::new();
    let _ = stream.read_to_end(&mut raw);
    let text = String::from_utf8_lossy(&raw);
    let (head, body) = text.split_once("\r\n\r\n")?;
    let status: u16 = head.split_whitespace().nth(1)?.parse().ok()?;
    let json = match (body.find('{'), body.rfind('}')) {
        (Some(s), Some(e)) if e >= s => body[s..=e].to_string(),
        _ => String::new(),
    };
    Some((status, json))
}

/// What [`apply`] did, for the launch log.
#[derive(Debug, Default, PartialEq, Eq)]
pub struct Applied {
    /// `mcp_tools` entries enabled for this launch.
    pub registered: Vec<String>,
    /// Generated files removed because their identity is gone or changed transport.
    pub removed: Vec<String>,
    /// Token env names that were set in neither the keychain nor the environment.
    pub missing_tokens: Vec<String>,
}

/// Register every RUNNING identity for this launch and clean up after gone
/// ones. Writes into `data_home` (the volume every container mounts as HOME):
/// `.nemesis8/mcp/ferricula-<name>.toml` for http, `mcp/ferricula-<name>.py`
/// for bridge, `.n8/ferricula/<name>.token` from the keychain when the token
/// is set. Then enables the servers: their entries go on `config.mcp_tools`,
/// their token env on `config.env.env_imports`.
pub fn apply(config: &mut crate::config::Config, data_home: &Path, identities: &[Identity]) -> Applied {
    apply_with(config, data_home, identities, &|name| {
        crate::secrets::get(name).ok().flatten().or_else(|| std::env::var(name).ok())
    })
}

/// [`apply`] with the token lookup injected (tests).
pub fn apply_with(
    config: &mut crate::config::Config,
    data_home: &Path,
    identities: &[Identity],
    token: &dyn Fn(&str) -> Option<String>,
) -> Applied {
    let mut applied = Applied::default();
    let servers_dir = crate::mcp_registry::host_user_mcp_dir(data_home);
    let tools_dir = data_home.join("mcp");
    let tokens_dir = data_home.join(".n8").join("ferricula");
    let running: Vec<&Identity> = identities.iter().filter(|i| i.is_running()).collect();

    // Stale generated files first, so an identity that stopped (or changed
    // transport) disappears. Only files carrying our mark are ever removed.
    let keep_toml: Vec<String> = running
        .iter()
        .filter(|i| i.transport() == Transport::Http)
        .map(|i| i.toml_file_name())
        .collect();
    let keep_py: Vec<String> = running
        .iter()
        .filter(|i| i.transport() == Transport::Bridge)
        .map(|i| i.bridge_file_name())
        .collect();
    applied.removed.extend(remove_stale(&servers_dir, ".toml", &keep_toml));
    applied.removed.extend(remove_stale(&tools_dir, ".py", &keep_py));

    for id in running {
        let entry = match id.transport() {
            Transport::Http => {
                if std::fs::create_dir_all(&servers_dir).is_err()
                    || !write_if_changed(&servers_dir.join(id.toml_file_name()), &id.toml())
                {
                    continue;
                }
                id.server_name()
            }
            Transport::Bridge => {
                let Some(source) = id.bridge.as_ref().and_then(|p| std::fs::read_to_string(p).ok()) else {
                    continue;
                };
                if std::fs::create_dir_all(&tools_dir).is_err()
                    || !write_if_changed(&tools_dir.join(id.bridge_file_name()), &id.bridge_wrapper(&source))
                {
                    continue;
                }
                id.bridge_file_name()
            }
        };
        match token(&id.token_env) {
            Some(t) if !t.trim().is_empty() => {
                if std::fs::create_dir_all(&tokens_dir).is_ok() {
                    let _ = write_if_changed(&tokens_dir.join(id.token_file_name()), t.trim());
                }
            }
            _ => {
                if !applied.missing_tokens.contains(&id.token_env) {
                    applied.missing_tokens.push(id.token_env.clone());
                }
            }
        }
        if !config.mcp_tools.contains(&entry) {
            config.mcp_tools.push(entry.clone());
        }
        if !config.env.env_imports.contains(&id.token_env) {
            config.env.env_imports.push(id.token_env.clone());
        }
        applied.registered.push(entry);
    }
    applied
}

/// Remove generated `ferricula-*<ext>` files in `dir` that are not in `keep`.
fn remove_stale(dir: &Path, ext: &str, keep: &[String]) -> Vec<String> {
    let mut removed = Vec::new();
    let Ok(rd) = std::fs::read_dir(dir) else {
        return removed;
    };
    for entry in rd.flatten() {
        let fname = entry.file_name().to_string_lossy().to_string();
        if !fname.starts_with("ferricula-") || !fname.ends_with(ext) || keep.contains(&fname) {
            continue;
        }
        let ours = std::fs::read_to_string(entry.path())
            .map(|s| s.lines().take(2).any(|l| l == GENERATED_MARK))
            .unwrap_or(false);
        if ours && std::fs::remove_file(entry.path()).is_ok() {
            removed.push(fname);
        }
    }
    removed
}

/// Write only on change: these dirs are bind mounts every container reads.
fn write_if_changed(path: &Path, content: &str) -> bool {
    if std::fs::read_to_string(path).ok().as_deref() == Some(content) {
        return true;
    }
    std::fs::write(path, content).is_ok()
}

/// The launch-time step: discover, probe, apply, and say what happened.
/// No-op when discovery is off. Returns the identities for callers that
/// display them.
pub fn discover_and_apply(runtime: &str, data_home: &Path, config: &mut crate::config::Config) -> Vec<Identity> {
    if !enabled(config) {
        return Vec::new();
    }
    let mut identities = discover(runtime);
    for id in identities.iter_mut().filter(|i| i.is_running()) {
        probe(id);
    }
    let applied = apply(config, data_home, &identities);
    for name in &applied.removed {
        tracing::info!("integration: ferricula identity gone or changed, removed {name}");
    }
    for id in identities.iter().filter(|i| i.is_running()) {
        let how = match id.transport() {
            Transport::Http => format!("http {}", id.container_url()),
            Transport::Bridge => format!("stdio bridge {}", id.bridge_file_name()),
        };
        tracing::info!(
            "integration: ferricula identity {} → MCP server `{}` via {} (mode {}, token env {})",
            id.name,
            id.server_name(),
            how,
            id.mode.as_deref().unwrap_or("unknown"),
            id.token_env
        );
    }
    for env in &applied.missing_tokens {
        eprintln!(
            "[nemesis8] warning: ferricula identity token `{env}` is set neither in the keychain nor this \
             environment — the agent will reach the identity unauthenticated. Store it with `n8 secrets set {env}`."
        );
    }
    identities
}

#[cfg(test)]
mod tests {
    use super::*;

    const STEVE_LINE: &str = "/steve-jobs-v2-test\trunning\t{\"com.docker.compose.service\":\"steve\",\"com.docker.compose.project.working_dir\":\"C:\\\\proj\\\\ferricula_v2\",\"ferricula.identity\":\"steve\",\"ferricula.mcp_port\":\"18875\",\"ferricula.mcp_path\":\"/mcp\",\"ferricula.token_env\":\"FERRICULA_OPERATOR_TOKEN\"}\t{\"8875/tcp\":[{\"HostIp\":\"127.0.0.1\",\"HostPort\":\"18875\"}]}";

    fn steve() -> Identity {
        parse_inspect_lines(STEVE_LINE).remove(0)
    }

    fn temp_home(tag: &str) -> PathBuf {
        let dir = std::env::temp_dir().join(format!("n8-ferricula-{tag}-{}", uuid::Uuid::new_v4()));
        std::fs::create_dir_all(&dir).unwrap();
        dir
    }

    #[test]
    fn parses_labelled_containers_and_skips_the_rest() {
        let text = format!(
            "{STEVE_LINE}\n/n8-fun-lark\trunning\t{{\"nemesis8.agent\":\"true\"}}\t{{}}\n/broken\trunning\tnot json\t{{}}\n"
        );
        let ids = parse_inspect_lines(&text);
        assert_eq!(ids.len(), 1);
        let s = &ids[0];
        assert_eq!(s.name, "steve");
        assert_eq!(s.container, "steve-jobs-v2-test");
        assert_eq!(s.host_port, 18875);
        assert_eq!(s.mcp_path, "/mcp");
        assert_eq!(s.bridge, None);
        assert_eq!(s.token_env, "FERRICULA_OPERATOR_TOKEN");
        assert_eq!(s.health_path, "/health");
        assert!(s.is_running());
        assert_eq!(s.container_url(), "http://host.docker.internal:18875/mcp");
        assert_eq!(s.host_url(), "http://127.0.0.1:18875/mcp");
        // No bridge: http regardless of the route probe.
        assert_eq!(s.transport(), Transport::Http);
        assert_eq!(s.tool_entry(), "steve");
    }

    #[test]
    fn port_falls_back_to_the_published_port_and_defaults_fill_in() {
        let line = "/wren\trunning\t{\"ferricula.identity\":\"Wren Two\"}\t{\"8875/tcp\":[{\"HostIp\":\"0.0.0.0\",\"HostPort\":\"18900\"}],\"9000/tcp\":null}";
        let ids = parse_inspect_lines(line);
        assert_eq!(ids.len(), 1);
        assert_eq!(ids[0].host_port, 18900);
        assert_eq!(ids[0].server_name(), "wren-two");
        assert_eq!(ids[0].toml_file_name(), "ferricula-wren-two.toml");
        assert_eq!(ids[0].bridge_file_name(), "ferricula-wren-two.py");
        // No port anywhere: not registrable.
        let none = "/x\trunning\t{\"ferricula.identity\":\"x\"}\t{}";
        assert!(parse_inspect_lines(none).is_empty());
    }

    #[test]
    fn a_relative_bridge_label_resolves_under_the_compose_project_dir() {
        let line = "/steve\trunning\t{\"ferricula.identity\":\"steve\",\"ferricula.bridge\":\"scripts/steve_mcp_bridge.py\",\"com.docker.compose.project.working_dir\":\"C:\\\\proj\\\\ferricula_v2\"}\t{\"8875/tcp\":[{\"HostIp\":\"127.0.0.1\",\"HostPort\":\"18875\"}]}";
        let id = parse_inspect_lines(line).remove(0);
        assert_eq!(id.bridge, Some(PathBuf::from("C:\\proj\\ferricula_v2").join("scripts/steve_mcp_bridge.py")));
        let abs = "/steve\trunning\t{\"ferricula.identity\":\"steve\",\"ferricula.bridge\":\"/srv/bridge.py\"}\t{\"8875/tcp\":[{\"HostIp\":\"127.0.0.1\",\"HostPort\":\"18875\"}]}";
        assert_eq!(parse_inspect_lines(abs).remove(0).bridge, Some(PathBuf::from("/srv/bridge.py")));
    }

    #[test]
    fn toml_is_a_registry_server_def_marked_as_generated() {
        let mut s = steve();
        s.agent_id = Some("ferricula-stevejobs".into());
        let toml = s.toml();
        assert!(toml.starts_with(GENERATED_MARK));
        let def: crate::mcp_def::McpServerDef = toml::from_str(&toml).expect("parses as a server def");
        assert_eq!(def.server.name, "steve");
        assert_eq!(def.server.url.as_deref(), Some("http://host.docker.internal:18875/mcp"));
        assert_eq!(def.server.bearer_token_env.as_deref(), Some("FERRICULA_OPERATOR_TOKEN"));
        assert_eq!(def.server.aliases, vec!["ferricula-steve"]);
        assert!(!def.server.is_stdio());
    }

    #[test]
    fn bridge_wrapper_keeps_shebang_and_future_imports_first() {
        let mut s = steve();
        s.bridge = Some(PathBuf::from("C:\\proj\\scripts\\steve_mcp_bridge.py"));
        let source = "#!/usr/bin/env python3\n\"\"\"doc\"\"\"\nfrom __future__ import annotations\nimport sys\nprint(sys.argv)\n";
        let wrapped = s.bridge_wrapper(source);
        let lines: Vec<&str> = wrapped.lines().collect();
        assert_eq!(lines[0], "#!/usr/bin/env python3");
        assert_eq!(lines[1], "\"\"\"doc\"\"\"");
        assert_eq!(lines[2], "from __future__ import annotations");
        assert_eq!(lines[3], GENERATED_MARK);
        assert!(wrapped.contains("_n8_os.environ.setdefault(\"FERRICULA_BASE_URL\", \"http://host.docker.internal:18875\")"));
        assert!(wrapped.contains("_n8_os.environ.setdefault(\"OLLAMA_BASE_URL\", \"http://host.docker.internal:11434\")"));
        assert!(wrapped.contains("_n8_os.environ.setdefault(\"FERRICULA_OPERATOR_TOKEN_FILE\", \"/opt/nemesis8/.n8/ferricula/steve.token\")"));
        assert!(wrapped.ends_with("print(sys.argv)\n"));
        // Plain script: the header goes first, after nothing.
        let plain = s.bridge_wrapper("import os\n");
        assert!(plain.starts_with(GENERATED_MARK));
        assert!(plain.ends_with("import os\n"));
    }

    #[test]
    fn apply_http_writes_enables_and_cleans_up_only_its_own_files() {
        let home = temp_home("http");
        let servers = crate::mcp_registry::host_user_mcp_dir(&home);
        std::fs::create_dir_all(&servers).unwrap();
        // A hand-written file with the ferricula- prefix must survive.
        std::fs::write(servers.join("ferricula-mine.toml"), "[server]\nname = \"mine\"\nurl = \"http://x/mcp\"\n").unwrap();
        // A stale generated one must go.
        std::fs::write(servers.join("ferricula-old.toml"), format!("{GENERATED_MARK}\n[server]\nname = \"old\"\n")).unwrap();

        let mut config = crate::config::Config::default();
        config.mcp_tools.push("nuts-files".into());
        let lookup = |name: &str| (name == "FERRICULA_OPERATOR_TOKEN").then(|| "hyp-operator-token".to_string());
        let applied = apply_with(&mut config, &home, &[steve()], &lookup);
        assert_eq!(applied.registered, vec!["steve"]);
        assert_eq!(applied.removed, vec!["ferricula-old.toml"]);
        assert!(applied.missing_tokens.is_empty());
        assert!(servers.join("ferricula-steve.toml").is_file());
        assert!(servers.join("ferricula-mine.toml").is_file());
        assert!(!servers.join("ferricula-old.toml").exists());
        assert_eq!(
            std::fs::read_to_string(home.join(".n8").join("ferricula").join("steve.token")).unwrap(),
            "hyp-operator-token"
        );
        assert_eq!(config.mcp_tools, vec!["nuts-files", "steve"]);
        assert_eq!(config.env.env_imports, vec!["FERRICULA_OPERATOR_TOKEN"]);

        // Idempotent: a second apply changes nothing.
        let again = apply_with(&mut config, &home, &[steve()], &lookup);
        assert_eq!(again.registered, vec!["steve"]);
        assert!(again.removed.is_empty());
        assert_eq!(config.mcp_tools, vec!["nuts-files", "steve"]);

        // Missing token: still registered, but reported.
        let mut other = crate::config::Config::default();
        let none = apply_with(&mut other, &home, &[steve()], &|_| None);
        assert_eq!(none.missing_tokens, vec!["FERRICULA_OPERATOR_TOKEN"]);
        assert_eq!(none.registered, vec!["steve"]);

        // Stopped identity: not enabled, and its generated file is removed.
        let mut stopped = steve();
        stopped.state = "exited".into();
        let mut fresh = crate::config::Config::default();
        let gone = apply_with(&mut fresh, &home, &[stopped], &lookup);
        assert!(gone.registered.is_empty());
        assert_eq!(gone.removed, vec!["ferricula-steve.toml"]);
        assert!(fresh.mcp_tools.is_empty());
        let _ = std::fs::remove_dir_all(&home);
    }

    #[test]
    fn apply_bridge_writes_a_wrapper_tool_and_flips_to_http_when_the_route_appears() {
        let home = temp_home("bridge");
        let script = home.join("steve_mcp_bridge.py");
        std::fs::write(&script, "#!/usr/bin/env python3\nimport os\nprint(os.environ.get('FERRICULA_BASE_URL'))\n").unwrap();
        let mut id = steve();
        id.bridge = Some(script.clone());
        id.mcp_status = Some(404); // the running image has no MCP route
        assert_eq!(id.transport(), Transport::Bridge);
        assert_eq!(id.tool_entry(), "ferricula-steve.py");

        let mut config = crate::config::Config::default();
        let lookup = |_: &str| Some("tok".to_string());
        let applied = apply_with(&mut config, &home, &[id.clone()], &lookup);
        assert_eq!(applied.registered, vec!["ferricula-steve.py"]);
        let wrapper = home.join("mcp").join("ferricula-steve.py");
        let text = std::fs::read_to_string(&wrapper).unwrap();
        assert!(text.lines().nth(1) == Some(GENERATED_MARK), "{text}");
        assert!(text.contains("FERRICULA_BASE_URL"));
        assert!(text.ends_with("print(os.environ.get('FERRICULA_BASE_URL'))\n"));
        assert!(!crate::mcp_registry::host_user_mcp_dir(&home).join("ferricula-steve.toml").exists());
        assert_eq!(config.mcp_tools, vec!["ferricula-steve.py"]);
        assert_eq!(config.env.env_imports, vec!["FERRICULA_OPERATOR_TOKEN"]);

        // The container was recreated with an MCP route: http takes over and
        // the wrapper is cleaned up.
        id.mcp_status = Some(401);
        assert_eq!(id.transport(), Transport::Http);
        let mut config = crate::config::Config::default();
        let flipped = apply_with(&mut config, &home, &[id.clone()], &lookup);
        assert_eq!(flipped.registered, vec!["steve"]);
        assert_eq!(flipped.removed, vec!["ferricula-steve.py"]);
        assert!(!wrapper.exists());
        assert!(crate::mcp_registry::host_user_mcp_dir(&home).join("ferricula-steve.toml").is_file());

        // A bridge label whose file is missing falls back to http too.
        id.mcp_status = Some(404);
        id.bridge = Some(home.join("nope.py"));
        assert_eq!(id.transport(), Transport::Http);
        let _ = std::fs::remove_dir_all(&home);
    }

    #[test]
    fn discovery_can_be_switched_off() {
        let mut config = crate::config::Config::default();
        assert!(enabled(&config));
        config.integrations.ferricula_discovery = Some(false);
        assert!(!enabled(&config));
        let dir = std::env::temp_dir().join(format!("n8-ferricula-off-{}", uuid::Uuid::new_v4()));
        let ids = discover_and_apply("definitely-not-a-container-runtime", &dir, &mut config);
        assert!(ids.is_empty());
        assert!(config.mcp_tools.is_empty());
        assert!(!dir.exists());
    }

    #[test]
    fn a_missing_runtime_discovers_nothing() {
        assert!(discover("definitely-not-a-container-runtime").is_empty());
    }
}
